# Generated by Django 3.0.2 on 2023-04-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='society',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Society'),
            preserve_default=False,
        ),
    ]
